PUR-48 aws s3 연동
Gong-Back/pureureum-server pull request #15
Opened 2023-10-30 14:41 UTC by yeongchan1228

## 📌 작업 이슈 번호
- [PUR-48](https://gongback.atlassian.net/browse/PUR-48)

## ✨ 작업 내용
- 파일 업로드 / 삭제 / preSignedUrl 조회

## ❗ 리뷰어에게 할 말
- infra 패키지와 도메인의 의존성을 분리하였습니다. 강결합을 맺지 않게 해 도메인에 의존적이지 않고 교체 가능성을 열어두었습니다.
- filePackage로 파일이 저장되는 패키지를 분리하였고, local / prod 환경을 분리해서 저장하도록 구현했습니다.

2023-11-07 01:46 UTC, Cl8D requested changes
고생하셨습니다~ 간단하게 리뷰 드렸는데 확인 부탁드려요 🙇‍♀️

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/controller/test/FileTestController.kt
> +@Tag(name = "04. File Test", description = "파일 테스트")
스웨거 부분은 나중에 인터페이스로 분리할 예정이신 거죠?!

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/controller/test/FileTestController.kt
> +        val fileExtension = FileExtractor.extractExtension(file.originalFilename!!)
원본 파일 이름이 항상 들어온다고 보장할 수는 없어서 Extractor 쪽에 file 자체를 넘기고 해당 부분에서 원본 파일 이름이 존재하는지에 대한 검증이 들어가면 좋을 것 같아요! (클래스 이름 자체가 `FileExtractor`인 만큼, 파일에서 특정한 정보를 추출하는 느낌이라 인자로 file이 넘어가는 게 더 자연스럽다고 느껴지기도 하구요!)

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/controller/test/FileTestController.kt
> +        fileClient.uploadFile(fileKey, file.inputStream, file.size, fileExtension)
이 부분도 개인적으로 객체로 분리해서 넘겨주면 좋을 것 같습니다! (인자의 개수가 많기도 하고 + 동일한 타입의 파라미터가 있기두도 하구요!)
해당 부분을 Extractor 쪽에서 처리하도록 위임해도 좋을 것 같아요!

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/infra/file/AwsS3Client.kt
> +    }
`getPreSignedUrl()`의 오타인가요 👀
혹시 오타라면, 개인적으로 preSigned라는 게 AWS S3에 종속적인 네이밍이라고 생각해서, getImageUrl() 처럼 조금 더 범용적인 함수명으로 가져가면 좋을 것 같아요!

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/infra/file/AwsS3Client.kt
> +    private fun getFileContentType(fileExtension: String) = "image/$fileExtension"
함수명은 FileContentType인데 실제로 반환하는 값은 이미지 타입에 종속적인 것 같아요! 
함수명을 이미지 전용으로 변경하는 게 좋을 것 같습니다!

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/service/FileExtractor.kt
> +}
싱글톤을 만족하는 게 목적이라면 object로 선언해서 사용해도 좋을 것 같습니다~!
```kotlin
object FileExtractor {
    fun extractExtension(originalFileName: String): String =
        originalFileName.substring(originalFileName.lastIndexOf(".") + 1)
}
`
``

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/support/constant/FilePackage.kt
> +    COMMON("공통"), ;
혹시 나중에 DB에 들어갈 부분인가요?
위에서 파일 패키지에 대한 생성기를 보았을 때 패키지는 항상 `dev-xxx`, `prod-xxx`와 같은 형식으로 만들어지는 것 같아서, COMMON 같은 상수 자체가 패키지 이름을 나타내는 건 아니라는 생각도 들었어요!

DB에서 파일 타입에 대한 컬럼으로도 함께 사용할 것이라면(공통인지 / 썸네일인지) 해당 네이밍은 패키지에 관련되어 있다 보니까 변경해도 좋을 것 같아요. DB에서 사용하지 않을 상수라면 상관없습니당!

2023-11-07 01:46 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/service/FileKeyGenerator.kt
> +        return "${getFilePackage(filePackage)}/${UUID.randomUUID()}.$fileExtension"
변수 추출을 하면 조금 더 읽기 쉬운 코드가 될 것 같아요! 😶

2023-11-07 12:00 UTC, yeongchan1228 commented on src/main/kotlin/gongback/pureureumserver/controller/test/FileTestController.kt
> +@Tag(name = "04. File Test", description = "파일 테스트")
테스트용 API라 코드에 바로 넣었습니다~

2023-11-07 12:11 UTC, yeongchan1228 commented on src/main/kotlin/gongback/pureureumserver/controller/test/FileTestController.kt
> +        fileClient.uploadFile(fileKey, file.inputStream, file.size, fileExtension)
`fileClient.uploadFile(fileKey, file.inputStream, file.size, fileExtension)` 이 부분의 인자를 말씀하시는 거면, infra 패키지가 다른 패키지들과 강결합을 가지지 않게 하기 위해서 DTO로 넘겨주는 것이 아닌 기본 타입으로 넘겨주고 있습니다!
외부 서비스에서 제공하는 기능만을 수행하게 하기 위한 곳으로 의존성을 분리하고 교체 가능하기 쉽도록 최대한 결합을 안 맺게 하려고 합니다!

2023-11-07 12:16 UTC, yeongchan1228 commented on src/main/kotlin/gongback/pureureumserver/infra/file/AwsS3Client.kt
> +    }
`PreSignedUrl`은 기본적인 ImageUrl이랑 다르게 만료 시간을 포함하고 있어 다른 의미를 가진다고 생각해 분리했었습니다. 말씀들어보니 조금 더 범용적으로 작성해도 괜찮겠네요!

2023-11-07 12:19 UTC, yeongchan1228 commented on src/main/kotlin/gongback/pureureumserver/support/constant/FilePackage.kt
> +    COMMON("공통"), ;
원래는 프로필, 게시글 이미지 등 의미를 가지는 패키지명을 지어주려고 했습니다! 
`COMMON`으로 작성한 이유는 S3 연동으로 테스트 느낌?으로 임시로 넣어둔 거 였는데, 오해할 수도 있다고 생각해 그냥 `Profile`로 변경했습니다 ㅎㅎ

2023-11-07 12:21 UTC, yeongchan1228 commented on src/main/kotlin/gongback/pureureumserver/service/FileKeyGenerator.kt
> +        return "${getFilePackage(filePackage)}/${UUID.randomUUID()}.$fileExtension"
클래스명 + 메서드명으로 충분히 어떤 값을 반환하는지 알 수 있을거라 생각했고, 변수로 추출하면 `Variable used only in following return and can be inlined` 밑줄이 그어져 인라인했었습니다!
이해하기 쉽도록 추출하겠습니다~

2023-11-07 12:24 UTC, yeongchan1228 commented on src/main/kotlin/gongback/pureureumserver/service/FileExtractor.kt
> +}
새로운 거 알아가네요!! 👍

2023-11-08 10:49 UTC, Cl8D approved these changes
고생하셨습니당!

2023-11-08 10:49 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/service/FileKeyGenerator.kt
> +        return fileKey
앗 변수로 추출해달라는 게 요런 느낌은 아니고.... 
`getFilePackage(filePackage)`, `${UUID.randomUUID()}` 와 같이 다른 함수를 호출하는 애들에 대해서 추출해달라는 의미였어요 🥹

2023-11-08 10:49 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/support/constant/FilePackage.kt
> +    PROFILE("프로필"), ;
요것도 내부 필드명이 아니라 `FilePackage`라는 enum class의 네이밍을 말씀드렸던 건데 의미가 잘못 전달되었던 것 같습니다 🥲...
나중에 entity의 필드값으로 `FilePackage`가 들어갔을 때 어색할 것 같다고 생각한 거였어요!

2023-11-08 10:49 UTC, Cl8D commented on src/main/kotlin/gongback/pureureumserver/controller/test/FileTestController.kt
> +        fileClient.uploadFile(fileKey, multipartFile.inputStream, multipartFile.size, fileExtension)
> infra 패키지가 다른 패키지들과 강결합을 가지지 않게 하기 위해서 DTO로 넘겨주는 것이 아닌 기본 타입으로 넘겨주고 있습니다!

지난 리뷰에서 이 답글은 잘 이해가 되지 않는데요!
domain -> infra로 강결합을 가지는 건 좋지 않지만, infra -> domain으로 결합을 가지는 건 상관없지 않나요?!
DTO를 infra 쪽이 아닌 `fileClient` 인터페이스가 존재하는 클래스에 존재하도록 만들어서, controller <-[DTO 전달]-> service <-[구현체로서 DTO 사용]-> ]infra 모두가 사용할 수 있도록 만드는 게 목적이었어요!

2023-11-13 12:48 UTC, merged